using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using ServiceClients;

namespace ConsoleApp1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            //setup our DI
            var services = new ServiceCollection();

            services.AddHttpClient<IPetShopServiceClient, PetShopServiceClient>(
                (provider, client) =>
                {
                    // manually set the base address
                    client.BaseAddress = new Uri("https://petstore.swagger.io/v2/");
                    /* further configuration can be made here */
                });

            // build provider
            var serviceProvider = services.BuildServiceProvider();

            // request the interface from our service provider
            var petShopServiceClient = serviceProvider.GetService<IPetShopServiceClient>();

            // use our autogenerated client with methods and classes to retrieve a pet by id
            var pet = await petShopServiceClient.GetPetByIdAsync(9892634);

            Console.WriteLine($"{pet.Name} | #{pet.Id}");
        }
    }
}
